apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
commonAnnotations:
  environment: dev
images:
  - name: app
    newName: localhost:5000/my-test-ubuntu-app
    newTag: "latest"
    digest: 
patchesStrategicMerge:
  - deployment.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: dev-troubleshooting-app # set the namespace
    unsetOnly: true
